pr: none
trigger: none

# Customize build number to include major version
# Example: v9_20201022.1
name: 'v9_$(Date:yyyyMMdd)$(Rev:.r)'

variables:
  - group: 'Github and NPM secrets'
  - template: ../templates/variables.yml
    parameters:
      skipComponentGovernanceDetection: false
  - name: release.vnext # Used to scope beachball to release only vnext packages
    value: true

pool: 'Self Host Ubuntu'

# TODO figure out how often to release v9
# schedules:
#   # minute 0, hour 4 in UTC (5am in UTC+1), any day of month, any month, days 1-5 of week (M-F)
#   # https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?tabs=yaml&view=azure-devops#supported-cron-syntax
#   - cron: '0 4 * * 1-5'
#     displayName: 'Daily release (M-F at 5am UTC+1)'
#     branches:
#       include:
#         - master

workspace:
  clean: all

steps:
  - template: ../templates/tools.yml

  - template: ../templates/yarn-install.yml

  - template: ../templates/release/git-auth.yml

  - template: ../templates/release/build-test-lint.yml

  - template: ../templates/release/beachball-publish.yml

  # TODO update release notes script for v9
  # - script: |
  #     node -r ./scripts/ts-node-register ./scripts/updateReleaseNotes/index.ts --token=$(githubPAT) --apply --debug
  #   displayName: 'Update github release notes'

  # This would usually be run automatically (via a pipeline decorator from an extension), but the
  # thorough cleanup step prevents it from working. So run it manually here.
  - template: ../templates/release/component-governance.yml

  - template: ../templates/cleanup.yml
    parameters:
      checkForModifiedFiles: false
